name Branches

env:
  ECR_REGISTRY: 942095822719.dkr.ecr.eu-west-2.amazonaws.com
  ECR_REPOSITORY: vn-dashboard

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: KL-Engineering/kidsloop-action-center/.github/actions/gocache@main
        with:
          GIT_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build Go
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image to Amazon ECR
        run: |
          set +x
          export VERSION_TAG=$(echo "v${{ steps.package-version.outputs.current-version }}")
          export BRANCH_TAG=$(echo "${GITHUB_REF_NAME}" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
          docker build -t $ECR_REPOSITORY:$BRANCH_TAG-latest .
          docker tag $ECR_REPOSITORY:$BRANCH_TAG-latest $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-latest
          docker tag $ECR_REPOSITORY:$BRANCH_TAG-latest $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-$VERSION_TAG
          docker tag $ECR_REPOSITORY:$BRANCH_TAG-latest $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-${GITHUB_SHA::7}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-$VERSION_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-${GITHUB_SHA::7}